/**
 * Strain Library data access — wraps data/strains/site-strains.json
 * (generated by scripts/generate-site-strains.mjs; committed like the
 * merge plan so builds stay hermetic).
 *
 * 10,600+ terpene-bearing strains. Server-side only — never import this
 * from a client component (the dataset is ~3.6 MB).
 */

import siteStrains from "@/data/strains/site-strains.json";

export interface StrainProduct {
    slug: string;
    name: string;
    path: string;
    category: string;
    price: number | null;
}

export interface StrainTerpene {
    name: string;
    /** dominance from lab aggregation; terpenes[] is sorted high→low */
    level?: "high" | "medium" | "low";
}

export interface SiteStrain {
    slug: string;
    name: string;
    type: string; // INDICA | SATIVA | HYBRID
    terpenes: StrainTerpene[];
    effects: string[];
    products: StrainProduct[];
    thcMin?: number;
    thcMax?: number;
    cbdMax?: number;
    indicaPercent?: number;
    sativaPercent?: number;
    lineage?: string;
    flavors?: string[];
    aliases?: string[];
    popularityScore?: number;
}

// The 3.6 MB JSON's inferred literal type is enormous — cast through
// unknown; SiteStrain documents the actual record shape.
const STRAINS = (siteStrains as unknown as { strains: SiteStrain[] }).strains;

const bySlug = new Map(STRAINS.map((s) => [s.slug, s]));

// product slug → strain (first strain that lists the product)
const byProductSlug = new Map<string, SiteStrain>();
for (const s of STRAINS) {
    for (const p of s.products) {
        if (!byProductSlug.has(p.slug)) byProductSlug.set(p.slug, s);
    }
}

// ── Terpene bitmasks for fast profile-similarity (13 known terpenes) ──

const TERPENE_BIT = new Map<string, number>();
const maskOf = (s: SiteStrain): number => {
    let m = 0;
    for (const t of s.terpenes) {
        let bit = TERPENE_BIT.get(t.name);
        if (bit === undefined) {
            bit = 1 << TERPENE_BIT.size;
            TERPENE_BIT.set(t.name, bit);
        }
        m |= bit;
    }
    return m;
};
const MASKS = new Map<string, number>(STRAINS.map((s) => [s.slug, maskOf(s)]));

function popcount(x: number): number {
    let c = 0;
    while (x) { x &= x - 1; c++; }
    return c;
}

export function getAllSiteStrains(): SiteStrain[] {
    return STRAINS;
}

export function getSiteStrainBySlug(slug: string): SiteStrain | undefined {
    return bySlug.get(slug);
}

export function getStrainForProduct(productSlug: string): SiteStrain | undefined {
    return byProductSlug.get(productSlug);
}

export function terpeneNames(s: SiteStrain): string[] {
    return s.terpenes.map((t) => t.name);
}

/**
 * Closest strains by terpene-profile overlap (Jaccard on terpene sets,
 * same-type bonus, popularity tiebreak). ~10k bitmask ops per call —
 * sub-millisecond.
 */
export function getSimilarStrains(strain: SiteStrain, limit = 4): SiteStrain[] {
    const mine = MASKS.get(strain.slug) ?? 0;
    if (!mine) return [];
    const scored: { s: SiteStrain; score: number; pop: number }[] = [];
    for (const o of STRAINS) {
        if (o.slug === strain.slug) continue;
        const m = MASKS.get(o.slug)!;
        const inter = popcount(mine & m);
        if (inter === 0) continue;
        const union = popcount(mine | m);
        const score = inter / union + (o.type === strain.type ? 0.1 : 0) + (o.products.length > 0 ? 0.05 : 0);
        scored.push({ s: o, score, pop: o.popularityScore || 0 });
    }
    scored.sort((a, b) => b.score - a.score || b.pop - a.pop);
    return scored.slice(0, limit).map((x) => x.s);
}

/** Strains that carry live products — the featured set. */
export function getFeaturedStrains(): SiteStrain[] {
    return STRAINS.filter((s) => s.products.length > 0);
}

/** Most popular strains of a type (for the index page sections). */
export function getTopStrainsByType(type: string, limit = 24): SiteStrain[] {
    return STRAINS.filter((s) => s.type === type)
        .sort((a, b) => (b.popularityScore || 0) - (a.popularityScore || 0) || b.terpenes.length - a.terpenes.length)
        .slice(0, limit);
}

/** A–Z browse: first letter (digits grouped under "0"). */
export function letterOf(s: SiteStrain): string {
    const c = (s.name[0] || "#").toLowerCase();
    return c >= "a" && c <= "z" ? c : "0";
}

export function getStrainsByLetter(letter: string): SiteStrain[] {
    const l = letter.toLowerCase();
    return STRAINS.filter((s) => letterOf(s) === l).sort((a, b) => a.name.localeCompare(b.name));
}

export function getLetterCounts(): { letter: string; count: number }[] {
    const counts = new Map<string, number>();
    for (const s of STRAINS) {
        const l = letterOf(s);
        counts.set(l, (counts.get(l) || 0) + 1);
    }
    return [..."0abcdefghijklmnopqrstuvwxyz"]
        .filter((l) => counts.has(l))
        .map((l) => ({ letter: l, count: counts.get(l)! }));
}

/** Display label for the strain type chip. */
export function strainTypeLabel(s: SiteStrain): string {
    if (s.indicaPercent && s.sativaPercent) {
        return `${s.type} · ${s.indicaPercent}% indica / ${s.sativaPercent}% sativa`;
    }
    return s.type.charAt(0) + s.type.slice(1).toLowerCase();
}
