/**
 * Strain Library data access — wraps data/strains/site-strains.json
 * (generated by scripts/generate-site-strains.mjs; committed like the
 * merge plan so builds stay hermetic).
 */

import siteStrains from "@/data/strains/site-strains.json";

export interface StrainProduct {
    slug: string;
    name: string;
    path: string;
    category: string;
    price: number | null;
}

export interface SiteStrain {
    slug: string;
    name: string;
    type: string; // INDICA | SATIVA | HYBRID
    thcMin: number | null;
    thcMax: number | null;
    cbdMax: number | null;
    indicaPercent: number | null;
    sativaPercent: number | null;
    aliases: string[];
    popularityScore: number;
    terpenes: string[];
    effects: string[];
    products: StrainProduct[];
    similar: string[];
}

const STRAINS = (siteStrains as { strains: SiteStrain[] }).strains;

const bySlug = new Map(STRAINS.map((s) => [s.slug, s]));

// product slug → strain (first strain that lists the product)
const byProductSlug = new Map<string, SiteStrain>();
for (const s of STRAINS) {
    for (const p of s.products) {
        if (!byProductSlug.has(p.slug)) byProductSlug.set(p.slug, s);
    }
}

export function getAllSiteStrains(): SiteStrain[] {
    return STRAINS;
}

export function getSiteStrainBySlug(slug: string): SiteStrain | undefined {
    return bySlug.get(slug);
}

export function getStrainForProduct(productSlug: string): SiteStrain | undefined {
    return byProductSlug.get(productSlug);
}

export function getSimilarStrains(strain: SiteStrain): SiteStrain[] {
    return strain.similar
        .map((slug) => bySlug.get(slug))
        .filter((s): s is SiteStrain => Boolean(s));
}

/** Display label for the strain type chip. */
export function strainTypeLabel(s: SiteStrain): string {
    if (s.indicaPercent && s.sativaPercent) {
        return `${s.type} · ${s.indicaPercent}% indica / ${s.sativaPercent}% sativa`;
    }
    return s.type.charAt(0) + s.type.slice(1).toLowerCase();
}
